<?php
/**
 * @author Thomas Tourlourat <thomas@tourlourat.com>
 */

namespace Dayuse\Istorija\Process\Testing;

use Dayuse\Istorija\CommandBus\CommandBus;
use Dayuse\Istorija\CommandBus\NullCommandBus;
use Dayuse\Istorija\CommandBus\TraceableCommandBus;
use Dayuse\Istorija\DAO\Storage\InMemoryDAO;
use Dayuse\Istorija\Process\Process;
use Dayuse\Istorija\Process\StateRepository;
use Dayuse\Istorija\Process\StateRepositoryDAO;
use PHPUnit\Framework\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    /**
     * @var Scenario
     */
    protected $scenario;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $commandBus = new TraceableCommandBus(new NullCommandBus());
        $process    = $this->createProcess(
            $commandBus,
            new StateRepositoryDAO(new InMemoryDAO())
        );

        $this->scenario = new ScenarioPHPUnit($process, $commandBus, $this);
    }

    abstract protected function createProcess(CommandBus $commandBus, StateRepository $repository): Process;
}